### PR TITLE
MACS data

### PR DESCRIPTION
**Pull request by krishnakalyan3**
[MACS](https://zenodo.org/record/5114771#.yq4kbnbmlb1) data processing pipeline.

TODO:
- [x] Download Script
- [x] Upload to raw_data `s3://s-laion-audio/raw_dataset/MACS`
- [x] Data Preprocess Script
- [ ] Custom Split
- [ ] Upload to webdataset_tar `s3://s-laion-audio/webdataset_tar/MACS`
- [ ] Data Card

MACS dataset is an augmented version of the [TAU Urban Acoustic Scenes 2019](https://zenodo.org/record/2589280#.YxMMp-xBztU) dataset

### CODE REVIEW

**Comment by krishnakalyan3** [comment]
cc: @marianna13 for review.

@YuchenHui22314 looks like we already have this dataset [here](https://github.com/LAION-AI/audio-dataset/blob/main/download_script/download_TAU-Multiannotator.sh) perhaps we should deduplicate?

**Comment by YuchenHui22314** [comment]
> cc: @marianna13 for review.
> 
> @YuchenHui22314 looks like we already have this dataset [here](https://github.com/LAION-AI/audio-dataset/blob/main/download_script/download_TAU-Multiannotator.sh) perhaps we should deduplicate?

Oh, it seems that they are deleted afterwards. However, you can redownload them using this script

**Comment by krishnakalyan3** [comment]
@YuchenHui22314 @marianna13 could you please review every thing that is done so far?.

I am not sure about the following
-  Can you please point me to existing code using to split the data. This is a dataset without any splits. Where is this code checked in? 
- After splitting the dataset I would need to convert to `webdataset_tar`. The total number of pairs in this dataset is `3930`. Does `-num_element 512` sound good for this dataset?. Should this command below also be part of this github repo somewhere?
 
```python make_tar.py --input /fsx/MACS/processed_datasets --output /fsx/MACS/processed_datasets/webdataset_tar/ --dataclass all --num_element 512 --filename MCAS```

**Comment by YuchenHui22314** [comment]
@krishnakalyan3 Please check dircord message

**Pull request closed without merging**
